### ISSUE TITLE
安装最新的macos12出些一些问题

### ISSUE THREAD

**Issue by scfff** [wxjiyc/FunHouse-F10-MPro-1005G1-Hackintosh#1]
启动系统logo界面进度条走一半，然后要卡好几分钟才能进入系统。进系统后ax201网卡无法驱动，usb无法读取U盘。
不知道是不是我哪里设置有问题呢？

**Comment by wxjiyc** [comment]
暂不支持macOS 12

**Comment by wxjiyc** [comment]
> 启动系统logo界面进度条走一半，然后要卡好几分钟才能进入系统。进系统后ax201网卡无法驱动，usb无法读取U盘。 不知道是不是我哪里设置有问题呢？
暂不支持macOS 12

**Comment by scfff** [comment]
好吧，谢谢你
